-- 줄바꿈 시 enter -> 명령어 완성이라고 생각하여 JPA Exception 발생
-- Categories
insert into categories (category_name, parent_category_id) values("음식", null);
insert into categories (category_name, parent_category_id) values("스포츠", null);
insert into categories (category_name, parent_category_id) values("빵", 1);
insert into categories (category_name, parent_category_id) values("카레빵", 3);
insert into categories (category_name, parent_category_id) values("소세지빵", 3);

-- Products
-- insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, NOW() - 100, 1, null, 5000, 'test_product_desc1', 'test_product1', 100, 0);
-- insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, NOW() - 200, 1, null, 200000, 'test_product_desc2', 'test_product2', 400, 0);
-- insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, NOW() - 500, 2, null, 50000, 'test_product_desc3', 'test_product3', 500, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 5, null, 2093675, 'test_product_desc1', 'test_product1', 5089, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 2, null, 2257373, 'test_product_desc2', 'test_product2', 6558, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 2, null, 7015907, 'test_product_desc3', 'test_product3', 5657, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 4, null, 5937384, 'test_product_desc4', 'test_product4', 8233, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 4, null, 7887614, 'test_product_desc5', 'test_product5', 8781, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 5, null, 6275607, 'test_product_desc6', 'test_product6', 2981, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 1, null, 8151445, 'test_product_desc7', 'test_product7', 5894, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 3, null, 4317832, 'test_product_desc8', 'test_product8', 2885, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 1, null, 1300887, 'test_product_desc9', 'test_product9', 4459, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 1, null, 2692366, 'test_product_desc10', 'test_product10', 5673, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 5, null, 2414986, 'test_product_desc11', 'test_product11', 5797, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 3, null, 9391067, 'test_product_desc12', 'test_product12', 7288, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 5, null, 4281702, 'test_product_desc13', 'test_product13', 5222, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 3, null, 9872363, 'test_product_desc14', 'test_product14', 2400, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 4, null, 592206, 'test_product_desc15', 'test_product15', 1505, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 1, null, 440240, 'test_product_desc16', 'test_product16', 6461, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 3, null, 8596403, 'test_product_desc17', 'test_product17', 1112, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 3, null, 9311378, 'test_product_desc18', 'test_product18', 2168, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 3, null, 1304034, 'test_product_desc19', 'test_product19', 8510, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 2, null, 8528241, 'test_product_desc20', 'test_product20', 4179, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 2, null, 4760354, 'test_product_desc21', 'test_product21', 7054, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 5, null, 9524750, 'test_product_desc22', 'test_product22', 988, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 1, null, 4058905, 'test_product_desc23', 'test_product23', 7359, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 2, null, 87418, 'test_product_desc24', 'test_product24', 9256, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 4, null, 6063958, 'test_product_desc25', 'test_product25', 6118, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 5, null, 1744127, 'test_product_desc26', 'test_product26', 9212, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 5, null, 8237146, 'test_product_desc27', 'test_product27', 9055, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 1, null, 5340917, 'test_product_desc28', 'test_product28', 5118, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 5, null, 3816583, 'test_product_desc29', 'test_product29', 5160, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 4, null, 6368837, 'test_product_desc30', 'test_product30', 5149, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 4, null, 18720, 'test_product_desc31', 'test_product31', 7765, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 5, null, 4256274, 'test_product_desc32', 'test_product32', 8930, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 3, null, 7735362, 'test_product_desc33', 'test_product33', 1482, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 3, null, 4023171, 'test_product_desc34', 'test_product34', 1795, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 2, null, 9337877, 'test_product_desc35', 'test_product35', 8335, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 4, null, 9253367, 'test_product_desc36', 'test_product36', 7294, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 4, null, 7168527, 'test_product_desc37', 'test_product37', 7252, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 3, null, 9419610, 'test_product_desc38', 'test_product38', 5050, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 1, null, 5420766, 'test_product_desc39', 'test_product39', 4837, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 3, null, 2983865, 'test_product_desc40', 'test_product40', 4210, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 1, null, 1911786, 'test_product_desc41', 'test_product41', 3789, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 4, null, 5803397, 'test_product_desc42', 'test_product42', 7794, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 2, null, 2660093, 'test_product_desc43', 'test_product43', 6074, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 3, null, 2660617, 'test_product_desc44', 'test_product44', 590, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 4, null, 5892781, 'test_product_desc45', 'test_product45', 6756, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 1, null, 2620097, 'test_product_desc46', 'test_product46', 134, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 4, null, 1637305, 'test_product_desc47', 'test_product47', 8373, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 5, null, 8019488, 'test_product_desc48', 'test_product48', 3203, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 3, null, 2597162, 'test_product_desc49', 'test_product49', 2525, 0);
insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), 4, null, 9787749, 'test_product_desc50', 'test_product50', 9252, 0);


-- Members
insert into members(modified_date, registration_date, birth_date, email, nickname, password, phone, role, social_flag, active, member_id) values(null, NOW() - 100, '1999-08-24', 'admin@naver.com', 'admin', 'admin', '010-5555-0302', 1, false, true, 0x0FCCD174645B4C3089F4E554712D6D7D);
insert into members(modified_date, registration_date, birth_date, email, nickname, password, phone, role, social_flag, active, member_id) values(null, NOW() - 4, '2002-03-12', 'test@naver.com', 'test', 'test', '010-1155-0302', 0, false, true, 0xB51DB8A571AB41518E81CE31BCEBA501);

-- Orders
insert into orders(modified_date, registration_date, buyer_id, delivery_address, delivery_address_detail, delivery_date, is_deleted, order_status, product_id, quantity, recipient_name, recipient_phone, order_id) values(null, NOW(), 0xB51DB8A571AB41518E81CE31BCEBA501, '서울', '강남구', null, 0x00, 0x00, 1, 10, '김태현', '010-4444-2222', 0x72B749DA3BD9403580D37ECCCE104D60);
insert into orders(modified_date, registration_date, buyer_id, delivery_address, delivery_address_detail, delivery_date, is_deleted, order_status, product_id, quantity, recipient_name, recipient_phone, order_id) values(null, NOW(), 0xB51DB8A571AB41518E81CE31BCEBA501, '울산 동구', '방어진', null, 0x00, 0x00, 1, 40, '김태현', '010-1114-2442', 0xe014e03e0d4e47338938d5e8c2917039);

-- delivery_info
insert into delivery_info(info_id, modified_date, registration_date, delivery_address, delivery_address_detail, recipient_name, recipient_phone, member_id) values(0xefe72099fd144aaea82233cc8db94b02, null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), '서울 서대문구 통일로 81 (NH농협생명빌딩)', '5층', '김태태', '010-1111-2340', 0xB51DB8A571AB41518E81CE31BCEBA501);
insert into delivery_info(info_id, modified_date, registration_date, delivery_address, delivery_address_detail, recipient_name, recipient_phone, member_id) values(0xa48f2629fdb64334a66fb87ce14ec807, null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), '서울 서대문구 통일로 81 (NH농협생명빌딩)', '2층', '김투투', '010-2222-4240', 0xB51DB8A571AB41518E81CE31BCEBA501);
insert into delivery_info(info_id, modified_date, registration_date, delivery_address, delivery_address_detail, recipient_name, recipient_phone, member_id) values(0x08ba395f37b848b1a83342abb238f454, null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), '서울 서대문구 통일로 81 (NH농협생명빌딩)', '11층', '김현현', '010-3333-5042', 0xB51DB8A571AB41518E81CE31BCEBA501);

-- for i in range(1, 51):
--     print("insert into products(modified_date, registration_date, category_id, manufacture_date, price, product_description, product_name, stock, view_count) values(null, DATE_ADD(CURRENT_DATE(), INTERVAL -FLOOR(RAND() * 365) DAY), {0}, null, {1}, 'test_product_desc{2}', 'test_product{2}', {3}, 0);".format(random.randint(1, 5), random.randint(5000, 10000000), i, random.randint(10, 10000)))